name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/erulabs243/agrotai-backend/
            git pull origin main
            git status
            
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Start production
        uses: borales/actions-yarn@v4
        with:
          cmd: start
